sudo: required
# language: csharp
# solution: web-app.sln

services:
    - docker 

before_install:
    - docker build -t web-app -f ./WebApplication/Dockerfile .


scripts: 
    -  docker run -d web-app