sudo: required
language: csharp
solution: web-app.sln

mono: none
dotnet: 3.1.302
script:
 - dotnet restore


 install:
    - nuget restore web-app.sln
    - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  script:
    - msbuild /p:Configuration=Release solution-name.sln
    - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Test/bin/Release/Test.dll

# services:

#     - docker 

# before_install:
#     - docker build -t web-app -f ./WebApplication/Dockerfile .


# scripts: 
#     -  docker run -d web-app